codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false

flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: map
      paths:
        - kv
    - name: list
      paths:
        - list
    - name: set
      paths:
        - set
    - name: queue
      paths:
        - queue
    - name: tree
      paths:
        - tree

ignore:
  - tree/*_node.go